project:
  type: book
  output-dir: docs

book:
  title: "Data Science con Python"
  author: "Daniel P."
  date: "today"
  chapters:
    - index.qmd
    - agradecimientos.qmd
    - introduccion.qmd
    - part: "I: Fundamentos y herramientas clave" # Opcional
      chapters:
        - 01.elementos-de-python.qmd
        - 02.estructuras-de-datos.qmd

    #- part: "II: Programaci√≥n Orientada a Objetos" # Opcional
    #  chapters:
    #    - capitulo-2/01-funciones/01-definicion.qmd
    #    - capitulo-2/01-funciones/02-parametros.qmd

#bibliography: references.bib

format:
  html:
    theme: cosmos

editor: visual